SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_SERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_SERVICO` (
  `TSE_PK_ID` INT NOT NULL AUTO_INCREMENT,
  `TSE_DESCRICAO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TSE_PK_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CIDADE` (
  `CID_PK_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CID_PK_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENDERECO` (
  `END_PK_ID` INT NOT NULL AUTO_INCREMENT,
  `END_DESCRICAO` VARCHAR(100) NOT NULL,
  `CID_FK_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`END_PK_ID`),
  INDEX `fk_ENDERECO_CIDADE1_idx` (`CID_FK_ID` ASC),
  CONSTRAINT `fk_ENDERECO_CIDADE1`
    FOREIGN KEY (`CID_FK_ID`)
    REFERENCES `mydb`.`CIDADE` (`CID_PK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PESSOA` (
  `PES_PK_ID` INT NOT NULL AUTO_INCREMENT,
  `PES_TIPO` VARCHAR(45) NULL,
  `PES_NOME` VARCHAR(45) NULL,
  `PES_SEXO` VARCHAR(1) NULL,
  `PES_DATA_NASC` DATE NULL,
  `PES_CPF` INT(11) NULL,
  `PES_CNPJ` INT(14) NULL,
  `PES_RG` INT NULL,
  `PES_RAZAO_SOCIAL` VARCHAR(100) NULL,
  `END_FK_ID` INT NOT NULL,
  PRIMARY KEY (`PES_PK_ID`),
  INDEX `fk_PESSOA_ENDERECO1_idx` (`END_FK_ID` ASC),
  CONSTRAINT `fk_PESSOA_ENDERECO1`
    FOREIGN KEY (`END_FK_ID`)
    REFERENCES `mydb`.`ENDERECO` (`END_PK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVIÇO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVIÇO` (
  `SER_SER_ID` INT NOT NULL AUTO_INCREMENT,
  `SER_PRO_NOME` VARCHAR(100) NOT NULL,
  `SER_CLI_NOME` VARCHAR(100) NULL,
  `SER_DATA` DATE NULL,
  `SER_HORARIO` TIME NULL,
  `SER_DESC` INT NOT NULL,
  `TIS_FK_TSE_IDTSE` INT NOT NULL,
  `PES_FK_ID_PROFISSIONAL` INT NOT NULL,
  `PES_FK_ID_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`SER_SER_ID`),
  INDEX `fk_SERVIÇO_TIPO_SERVICO1_idx` (`TIS_FK_TSE_IDTSE` ASC),
  INDEX `fk_SERVIÇO_PESSOA1_idx` (`PES_FK_ID_PROFISSIONAL` ASC),
  INDEX `fk_SERVIÇO_PESSOA2_idx` (`PES_FK_ID_CLIENTE` ASC),
  CONSTRAINT `fk_SERVIÇO_TIPO_SERVICO1`
    FOREIGN KEY (`TIS_FK_TSE_IDTSE`)
    REFERENCES `mydb`.`TIPO_SERVICO` (`TSE_PK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVIÇO_PESSOA1`
    FOREIGN KEY (`PES_FK_ID_PROFISSIONAL`)
    REFERENCES `mydb`.`PESSOA` (`PES_PK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVIÇO_PESSOA2`
    FOREIGN KEY (`PES_FK_ID_CLIENTE`)
    REFERENCES `mydb`.`PESSOA` (`PES_PK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TELEFONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TELEFONE` (
  `TEL_PK_ID` INT NOT NULL,
  `TEL_TIPO` INT(2) NOT NULL,
  `TEL_NUMERO` INT(11) NULL,
  `PES_FK_ID` INT NOT NULL,
  PRIMARY KEY (`TEL_PK_ID`),
  INDEX `fk_TELEFONE_PESSOA1_idx` (`PES_FK_ID` ASC),
  CONSTRAINT `fk_TELEFONE_PESSOA1`
    FOREIGN KEY (`PES_FK_ID`)
    REFERENCES `mydb`.`PESSOA` (`PES_PK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTADO` (
  `UF_PK_ID` VARCHAR(2) NOT NULL,
  `CID_FK_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`UF_PK_ID`),
  INDEX `fk_ESTADO_CIDADE1_idx` (`CID_FK_ID` ASC),
  CONSTRAINT `fk_ESTADO_CIDADE1`
    FOREIGN KEY (`CID_FK_ID`)
    REFERENCES `mydb`.`CIDADE` (`CID_PK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
